### ISSUE TITLE
QML resources not found on Linux

### ISSUE THREAD

**Issue by kheaactua** [qCring/QuickVtk#6]
After I installed, the QuickVTK couldn't find `file:///home/matt/workspace/QuickVtk/Resources/qml/App/window.qml: File not found`

I found this file in `QuickVtk/res/qml/App/window.qml`, so I made a simlink to get around this for now.

**Comment by qCring** [comment]
Thanks for pointing that out! The steps for copying the resource directory (CMakeLists.txt 149-157)   only considered mac and windows. I just pushed a commit on the development branch. I hope this works now! Thanks for your contribution! :)

**Comment by qCring** [comment]
@kheaactua have you been able to reproduce this behavior from a more recent commit?

**Comment by kheaactua** [comment]
Giving it a try now, but it seems to now depend on VTK Renderer External which I did install.  Setting it up now (and fighting with apt-get for the GLUT dependencies. :)  )  I'll get back to you.

Oh, I still have to specify  `-DCMAKE_CXX_FLAGS="--std=c++11"`, maybe this should be defaulted?  (I'm on 14.04 using clang 3.8)

**Comment by qCring** [comment]
Awesome, thanks! Yes, VTK configuration changed a bit due to the now supported (and also default) OpenGL2 rendering backend. On mac and windows this means to rebulid VTK with `Module_vtkRenderingExternal=ON`. If there are more steps necessary on linux (like installing glut manually), that should be stated in the build instructions. 
And I'll go ahead and add the flag for c++11 right away, totally forgot about that. Thanks a lot for your contribution!

**Comment by kheaactua** [comment]
I've been having trouble building VTK.  I enabled the `Module_vtkRenderingExternal` module but am still missing some headers.  Ultimately though I no longer intend to use VTK for my application.. So I can't really spend more time testing this out. :(  Sorry about that.

**Comment by qCring** [comment]
No problem! Thanks for your time and effort! :)
